### ISSUE TITLE
Earth mobs mod incompatibility

### ISSUE THREAD

**Issue by felivans** [davidjjung/milkyway#6]
The milking timer from this mod does not affect Earth mobs mod's cows variants.
https://github.com/baguchan/EarthMobs

**Comment by davidjjung** [comment]
Hello! You have to add relevant mobs to the right tag via a datapack or [KubeJS script](https://wiki.latvian.dev/books/kubejs/page/tags). Let me know if they don't work after completing this step :]

**Comment by felivans** [comment]
> Hello! You have to add relevant mobs to the right tag via a datapack or [KubeJS script](https://wiki.latvian.dev/books/kubejs/page/tags). Let me know if they don't work after completing this step :]

Would it be too difficult to implement a mob whitelist that adds the required tags to the mobs?, alternately could you explain to me how and what tags to add via datapack (or point me to he correct resource to learn)?

**Comment by davidjjung** [comment]
It's not difficult as much as it would be unnecessary (and possibly less performant), as entity type tags are what vanilla uses in order to differentiate groups of mobs under certain conditions.

[This video](https://www.youtube.com/watch?v=R6vFbqYmET4) may provide some insight--I mostly learned datapacking through knowing mod file structures, which takes longer and is less accessible. The tag(s) you want to replace are [here](https://github.com/davidjjung/milkyway/tree/master/src/generated/resources/data/milky_way/tags/entity_types). You need to make sure to follow the same namespace (milky_way/tags/entity_types/whatever.json) to make sure it overrides my entity type tag json file in-game.

If none of that made any sense, I'd recommend using a KubeJS script. Alternatively, I'm sure there are many spaces on Discord where you can probably ask for help or guidance. Best of luck!
